// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Vector$Haxbool = require("../src/Vector.bs.js");

function floatsToFixedStrings(param) {
  return /* tuple */[
          param[0].toFixed(8),
          param[1].toFixed(8),
          param[2].toFixed(8)
        ];
}

Jest.describe("Vector.straightEquationCoefficients", (function (param) {
        Jest.test("Vertical straight (x = 2) - (2.0, 5.0), (2.0, 13.0)", (function (param) {
                return Jest.Expect.toEqual(/* tuple */[
                            1.0,
                            0.0,
                            -2.0
                          ], Jest.Expect.expect(Vector$Haxbool.straightEquationCoefficients(/* tuple */[
                                    2.0,
                                    5.0
                                  ], /* tuple */[
                                    2.0,
                                    13.0
                                  ])));
              }));
        Jest.test("Horizontal straight (y = 4) - (2.0, 4.0), (8.0, 4.0)", (function (param) {
                return Jest.Expect.toEqual(/* tuple */[
                            0.0,
                            1.0,
                            -4.0
                          ], Jest.Expect.expect(Vector$Haxbool.straightEquationCoefficients(/* tuple */[
                                    2.0,
                                    4.0
                                  ], /* tuple */[
                                    8.0,
                                    4.0
                                  ])));
              }));
        return Jest.test("Straight (2x + 7y - 13 = 0) - (4.0, 5.0/.7.0), (5.0, 3.0/.7.0)", (function (param) {
                      return Jest.Expect.toEqual(floatsToFixedStrings(/* tuple */[
                                      2.0 / 7.0,
                                      1.0,
                                      -13.0 / 7.0
                                    ]), Jest.Expect.expect(floatsToFixedStrings(Vector$Haxbool.straightEquationCoefficients(/* tuple */[
                                              4.0,
                                              5.0 / 7.0
                                            ], /* tuple */[
                                              5.0,
                                              3.0 / 7.0
                                            ]))));
                    }));
      }));

exports.floatsToFixedStrings = floatsToFixedStrings;
/*  Not a pure module */
