// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Scene$ReactHooksTemplate = require("./Scene.bs.js");
var Keyboard$ReactHooksTemplate = require("./Keyboard.bs.js");

function App(Props) {
  return React.createElement(Keyboard$ReactHooksTemplate.make, {
              children: React.createElement(Scene$ReactHooksTemplate.make, { })
            });
}

var make = App;

exports.make = make;
/* react Not a pure module */
