// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Scene$ReactHooksTemplate = require("./Scene.bs.js");

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, "hello"), React.createElement(Scene$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
