// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Keyboard(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "keyboard",
              tabIndex: 0,
              onKeyDown: (function (prim) {
                  console.log(prim);
                  return /* () */0;
                })
            }, children);
}

var make = Keyboard;

exports.make = make;
/* react Not a pure module */
