// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Scene(Props) {
  return React.createElement("svg", {
              height: "100%",
              width: "100%"
            }, React.createElement("circle", {
                  cx: "50%",
                  cy: "50%",
                  r: "50px",
                  stroke: "black",
                  strokeWidth: "5"
                }));
}

var make = Scene;

exports.make = make;
/* react Not a pure module */
