// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function namedStyle(styleClassName, name) {
  return name + (" " + styleClassName);
}

exports.namedStyle = namedStyle;
/* No side effect */
